[package]
name = "rust_data_structures"
version = "0.1.0"
authors = ["Sherif Ali Ahmad Mohamad <she7631@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
